

-- This will create the user for the db

	CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';


	GRANT 
		EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, 
		CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, 
		CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, 
		CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  
    
    ON *.* TO 'test'@'localhost' WITH GRANT OPTION;
